"""acceso de gestores a datos de clientes

Revision ID: 08bea3d01f88
Revises: 6019042e7569
Create Date: 2026-09-26 14:16:46.778766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08bea3d01f88'
down_revision: Union[str, None] = '6019042e7569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gestor_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('gestor_id', sa.UUID(), nullable=True),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('etiqueta', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gestor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gestor_access_codigo'), 'gestor_access', ['codigo'], unique=True)
    op.create_index(op.f('ix_gestor_access_gestor_id'), 'gestor_access', ['gestor_id'], unique=False)
    op.create_index(op.f('ix_gestor_access_owner_id'), 'gestor_access', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gestor_access_owner_id'), table_name='gestor_access')
    op.drop_index(op.f('ix_gestor_access_gestor_id'), table_name='gestor_access')
    op.drop_index(op.f('ix_gestor_access_codigo'), table_name='gestor_access')
    op.drop_table('gestor_access')
    # ### end Alembic commands ###
