"""esquema inicial

Revision ID: 363444e5926d
Revises: 
Create Date: 2026-09-20 23:09:38.613887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363444e5926d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('owner', 'team', 'gestor', name='roleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('numero_factura', sa.String(), nullable=True),
    sa.Column('proveedor_nombre', sa.String(), nullable=False),
    sa.Column('proveedor_nif', sa.String(), nullable=True),
    sa.Column('pagador_nombre', sa.String(), nullable=True),
    sa.Column('pagador_nif', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('base_imponible', sa.Float(), nullable=False),
    sa.Column('tipo_iva', sa.Float(), nullable=False),
    sa.Column('iva_deducible', sa.Boolean(), nullable=True),
    sa.Column('retencion_irpf_pct', sa.Float(), nullable=False),
    sa.Column('pagado', sa.Boolean(), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('archivo_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cliente_nombre', sa.String(), nullable=False),
    sa.Column('cliente_nif', sa.String(), nullable=True),
    sa.Column('emisor_nombre', sa.String(), nullable=False),
    sa.Column('emisor_nif', sa.String(), nullable=True),
    sa.Column('base_imponible', sa.Float(), nullable=False),
    sa.Column('tipo_iva', sa.Float(), nullable=False),
    sa.Column('exenta_iva', sa.Boolean(), nullable=True),
    sa.Column('motivo_exencion', sa.String(), nullable=True),
    sa.Column('retencion_irpf_pct', sa.Float(), nullable=False),
    sa.Column('cobrada', sa.Boolean(), nullable=True),
    sa.Column('fecha_cobro', sa.Date(), nullable=True),
    sa.Column('archivo_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
