"""datos de usuario: nif y cuota de autonomos

Revision ID: 6019042e7569
Revises: 363444e5926d
Create Date: 2026-09-23 23:38:43.915824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6019042e7569'
down_revision: Union[str, None] = '363444e5926d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nif', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cuota_autonomos_mensual', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cuota_autonomos_mensual')
    op.drop_column('users', 'nif')
    # ### end Alembic commands ###
