"""contactos recurrentes y direccion fiscal

Revision ID: a49fca0fa472
Revises: e767bd186992
Create Date: 2026-09-27 23:44:28.748260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a49fca0fa472'
down_revision: Union[str, None] = 'e767bd186992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contactos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('nif', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contactos_owner_id'), 'contactos', ['owner_id'], unique=False)
    op.add_column('invoices', sa.Column('concepto', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('cliente_direccion', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('emisor_direccion', sa.String(), nullable=True))
    op.add_column('users', sa.Column('direccion', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'direccion')
    op.drop_column('invoices', 'emisor_direccion')
    op.drop_column('invoices', 'cliente_direccion')
    op.drop_column('invoices', 'concepto')
    op.drop_index(op.f('ix_contactos_owner_id'), table_name='contactos')
    op.drop_table('contactos')
    # ### end Alembic commands ###
