"""add pagador y cobrador a facturas y gastos

Revision ID: e15828c0f72c
Revises: 
Create Date: 2026-09-12 21:50:53.849391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e15828c0f72c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('numero_factura', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('pagador_nombre', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('pagador_nif', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('retencion_irpf_pct', sa.Float(), nullable=False, server_default='0'))
    op.add_column('invoices', sa.Column('emisor_nombre', sa.String(), nullable=False))
    op.add_column('invoices', sa.Column('emisor_nif', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'emisor_nif')
    op.drop_column('invoices', 'emisor_nombre')
    op.drop_column('expenses', 'retencion_irpf_pct')
    op.drop_column('expenses', 'pagador_nif')
    op.drop_column('expenses', 'pagador_nombre')
    op.drop_column('expenses', 'numero_factura')
    # ### end Alembic commands ###
