"""rol builder y cola de documentos pendientes

Revision ID: e767bd186992
Revises: 08bea3d01f88
Create Date: 2026-09-27 23:08:33.248194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e767bd186992'
down_revision: Union[str, None] = '08bea3d01f88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Postgres permite añadir un valor a un ENUM dentro de una transacción desde la v12,
    # siempre que no se use ese valor en la misma transacción (aquí no se usa).
    op.execute("ALTER TYPE roleenum ADD VALUE IF NOT EXISTS 'builder'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos_pendientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('nombre_archivo', sa.String(), nullable=False),
    sa.Column('tipo_archivo', sa.String(), nullable=False),
    sa.Column('archivo', sa.LargeBinary(), nullable=True),
    sa.Column('datos_extraidos', sa.JSON(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('revisado_por', sa.UUID(), nullable=True),
    sa.Column('revisado_en', sa.DateTime(), nullable=True),
    sa.Column('motivo_rechazo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revisado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_pendientes_owner_id'), 'documentos_pendientes', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documentos_pendientes_owner_id'), table_name='documentos_pendientes')
    op.drop_table('documentos_pendientes')
    # ### end Alembic commands ###
    # Nota: Postgres no permite quitar un valor de un ENUM, así que 'builder' se queda
    # en el tipo roleenum aunque se revierta esta migración.
